# Generated by Django 5.2.7 on 2025-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(upload_to='about/', verbose_name='Фото')),
                ('resume', models.FileField(blank=True, upload_to='resume/', verbose_name='Резюме PDF')),
                ('github', models.URLField(blank=True)),
                ('vk', models.URLField(blank=True)),
                ('habr', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Навык')),
                ('icon', models.CharField(help_text='Название иконки (например: python, django)', max_length=50, verbose_name='Иконка')),
                ('level', models.IntegerField(default=50, verbose_name='Уровень (0-100)')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
