# Generated by Django 5.2.7 on 2025-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='vk',
            field=models.URLField(blank=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='habr',
            field=models.URLField(blank=True, verbose_name='Habr'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Резюме PDF'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
    ]
